volumes:
  db:

networks:
  api-network:
  database-network:

services:
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - backend
    networks:
      - api-network
  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/database?sslmode=disable
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - api-network
      - database-network
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./migration/init/init.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - database-network